version: '2'

services:
  ctfd:
    image: ctfd:latest
    container_name: ${COURSE}
    user: root
    restart: always
    ports:
      - ${EXTERNAL_PORT}:${INTERNAL_PORT}
    environment:
      - UPLOAD_FOLDER=/var/uploads
      - DATABASE_URL=mysql+pymysql://ctfd:ctfd@db/ctfd
      - REDIS_URL=redis://cache:6379
      - WORKERS=1
      - LOG_FOLDER=/var/log/CTFd
      - ACCESS_LOG=-
      - ERROR_LOG=-
      - REVERSE_PROXY=true
    volumes:
      - ${COURSEDIR}/${COURSE}/logs:/var/log/CTFd
      - ${COURSEDIR}/${COURSE}/uploads:/var/uploads
      - ${CTFD_DIR}:/opt/CTFd:ro
    depends_on:
      - db
    networks:
      swag_default:
      internal:

  db:
    image: mariadb:10.4.12
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=ctfd
      - MYSQL_USER=ctfd
      - MYSQL_PASSWORD=ctfd
      - MYSQL_DATABASE=ctfd
    volumes:
      - ${COURSEDIR}/${COURSE}/db/mysql:/var/lib/mysql
    networks:
      internal:
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]

  cache:
    image: redis:4
    restart: always
    volumes:
      - ${COURSEDIR}/${COURSE}/redis/data:/data
    networks:
      internal:

volumes:
  ctfd:
    external: true
  classes:
    external: true

networks:
  swag_default:
    external: true
  internal:
    internal: true
